### PR TITLE
Fix gradle building

### PR DESCRIPTION
**Pull request by Neui**
Fix building with gradle:

* `gradlew` is not executable by default, changed that
* It tries to find an [non-existent version](https://mvnrepository.com/artifact/com.android.tools.build/gradle) 2.3.0 of `com.android.tools.build.gradle`. Downgrading to `2.1.3` works.
* I (and probably others) can only download Android Build Tools `24.0.1`, not `24.0.0`, so also changed that.

It now builds but and I can run it on the desktop, but it is in ugly fullscreen and I don't know how to continue. But that is not the point of this. Couldn't test android due to the target SDK version and android images are just a bit too big for me to download.

### CODE REVIEW

**Comment by ZTube** [comment]
Due to my bad internet connection in France I can't change that until saturday, as updating the BuildTools version would force me to download them. Or is there any other way?

**Comment by Neui** [comment]
Not sure if Android SDK supports resumable downloads, but you can take your time. I can wait till you've time to test and merge it.

**Comment by ZTube** [comment]
Ok, now it should work

**Comment by ZTube** [comment]
Ok, now it should work

**Pull request merged**
